# Generated by Django 5.2.10 on 2026-01-19 03:31

import My_app.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_test_mode', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('webhook_url', models.URLField(blank=True)),
                ('supported_currencies', models.JSONField(default=list)),
                ('supported_countries', models.JSONField(default=list)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=2.9, max_digits=5)),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=0.3, max_digits=10)),
                ('settings', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Payment Gateway Settings',
                'verbose_name_plural': 'Payment Gateway Settings',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('broadcast_type', models.CharField(choices=[('announcement', 'Announcement'), ('alert', 'Alert'), ('update', 'System Update'), ('maintenance', 'Maintenance'), ('trading', 'Trading Alert')], default='announcement', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='KYCApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.FileField(upload_to='kyc/id_docs/')),
                ('selfie', models.ImageField(upload_to='kyc/selfies/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_apps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('folder', models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('trash', 'Trash')], default='inbox', max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Read', 'Read'), ('UnRead', 'UnRead')], default='UnRead', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlanUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_plan', models.CharField(max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('plan', models.CharField(choices=[('Starter', 'Starter - Basic features'), ('Pro', 'Pro - Advanced features'), ('Premium', 'Premium - All features + priority support'), ('Enterprise', 'Enterprise - Custom solutions')], default='Starter', max_length=50)),
                ('profile_picture', models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Gateway Transaction ID')),
                ('payment_gateway', models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('ALIPAY', 'Alipay'), ('STRIPE', 'Stripe'), ('RAZORPAY', 'Razorpay'), ('FLUTTERWAVE', 'Flutterwave'), ('PAYSTACK', 'Paystack'), ('SQUARE', 'Square'), ('CHECKOUT', 'Checkout.com'), ('ADYEN', 'Adyen'), ('NONE', 'None')], default='NONE', max_length=50)),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Gateway Raw Response')),
                ('gateway_status', models.CharField(blank=True, choices=[('CREATED', 'Created'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('SETTLED', 'Settled'), ('DECLINED', 'Declined'), ('VOIDED', 'Voided'), ('REFUNDED', 'Refunded'), ('CHARGEBACK', 'Chargeback'), ('EXPIRED', 'Expired')], max_length=50, null=True)),
                ('txn_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('TRANSFER', 'Transfer'), ('FEE', 'Fee'), ('BONUS', 'Bonus'), ('REFUND', 'Refund'), ('INTEREST', 'Interest'), ('CHARGEBACK', 'Chargeback'), ('REVERSAL', 'Reversal'), ('ADMIN_MOD', 'Admin Modification')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('CNY', 'Chinese Yuan'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('INR', 'Indian Rupee'), ('ZAR', 'South African Rand')], default='USD', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold'), ('REFUNDED', 'Refunded'), ('PARTIAL', 'Partially Completed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('reference', models.CharField(default=My_app.models.Transaction.generate_transaction_reference, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('ALIPAY', 'Alipay'), ('MASTERCARD', 'MasterCard'), ('VISA', 'Visa'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('STRIPE', 'Stripe'), ('CRYPTO', 'Cryptocurrency'), ('WALLET', 'Wallet Balance'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay'), ('SKRILL', 'Skrill'), ('NETELLER', 'Neteller'), ('ADMIN', 'Admin')], max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured data for payment details, user info, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Processing Fee')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Net Amount (Amount - Fee)')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate used for currency conversion', max_digits=10, null=True)),
                ('converted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Amount in base currency')),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flagged_reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='User IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Browser/Device Info')),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2, null=True)),
                ('webhook_attempts', models.PositiveIntegerField(default=0)),
                ('last_webhook_sent', models.DateTimeField(blank=True, null=True)),
                ('webhook_response', models.JSONField(blank=True, default=dict)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
                ('parent_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_transactions', to='My_app.transaction')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'permissions': [('view_all_transactions', 'Can view all transactions'), ('export_transactions', 'Can export transactions'), ('process_refunds', 'Can process refunds'), ('manage_chargebacks', 'Can manage chargebacks')],
            },
        ),
        migrations.CreateModel(
            name='BalanceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('change', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('BONUS', 'Bonus'), ('ADMIN_MOD', 'Admin Modification'), ('REFUND', 'Refund'), ('FEE', 'Fee'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_modifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_changes', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_changes', to='My_app.transaction')),
            ],
            options={
                'verbose_name': 'Balance Change',
                'verbose_name_plural': 'Balance Changes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('limit_type', models.CharField(choices=[('DAILY', 'Daily Limit'), ('WEEKLY', 'Weekly Limit'), ('MONTHLY', 'Monthly Limit'), ('PER_TRANSACTION', 'Per Transaction Limit')], max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('ALIPAY', 'Alipay'), ('MASTERCARD', 'MasterCard'), ('VISA', 'Visa'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('STRIPE', 'Stripe'), ('CRYPTO', 'Cryptocurrency'), ('WALLET', 'Wallet Balance'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay'), ('SKRILL', 'Skrill'), ('NETELLER', 'Neteller'), ('ADMIN', 'Admin')], max_length=50, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('CNY', 'Chinese Yuan'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('INR', 'Indian Rupee'), ('ZAR', 'South African Rand')], default='USD', max_length=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.01, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Transaction Limit',
                'verbose_name_plural': 'Transaction Limits',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balances', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WebSocketNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('TRANSACTION', 'Transaction'), ('BALANCE', 'Balance Update'), ('SYSTEM', 'System')], default='INFO', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websocket_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'created_at'], name='My_app_tran_user_id_75c03d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='My_app_tran_status_2c3942_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['txn_type'], name='My_app_tran_txn_typ_8733a8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference'], name='My_app_tran_referen_568213_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='My_app_tran_created_5eefa0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='My_app_tran_transac_fdb957_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['gateway_transaction_id'], name='My_app_tran_gateway_535e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_gateway'], name='My_app_tran_payment_7fb5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_method'], name='My_app_tran_payment_13f3d1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['currency'], name='My_app_tran_currenc_b6236e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['expires_at'], name='My_app_tran_expires_916e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_flagged'], name='My_app_tran_is_flag_f82b15_idx'),
        ),
        migrations.AddIndex(
            model_name='websocketnotification',
            index=models.Index(fields=['user', 'is_read'], name='My_app_webs_user_id_e04527_idx'),
        ),
    ]
