# Generated by Django 5.2.10 on 2026-01-19 11:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('TRANSACTION_APPROVE', 'Transaction Approved'), ('TRANSACTION_REJECT', 'Transaction Rejected'), ('KYC_APPROVE', 'KYC Approved'), ('KYC_REJECT', 'KYC Rejected'), ('BALANCE_UPDATE', 'Balance Updated'), ('USER_MODIFY', 'User Modified'), ('SYSTEM', 'System Action')], max_length=50)),
                ('description', models.TextField()),
                ('target_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='kycapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'KYC Application', 'verbose_name_plural': 'KYC Applications'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_transactions', 'Can view all transactions'), ('export_transactions', 'Can export transactions'), ('process_refunds', 'Can process refunds'), ('manage_chargebacks', 'Can manage chargebacks'), ('approve_transactions', 'Can approve transactions')], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RemoveField(
            model_name='kycapplication',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='kycapplication',
            name='selfie',
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='automated_check_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='document_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='document_expiry_date',
            field=models.DateField(default=datetime.date(2030, 1, 1)),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='document_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='document_issue_date',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='document_number',
            field=models.CharField(default='0000000000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID Card'), ('DRIVERS_LICENSE', "Driver's License"), ('RESIDENCE_PERMIT', 'Residence Permit'), ('VOTERS_ID', "Voter's ID")], default='ID Card', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='nationality',
            field=models.CharField(default='kenyan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to='kyc/address_proof/'),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='revision_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='selfie_with_document',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_selfies/'),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='verification_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='kyc_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='kyc_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='daily_deposit_limit',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='daily_transfer_limit',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='daily_withdrawal_limit',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_deposited',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_transferred',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancechange',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('BONUS', 'Bonus'), ('ADMIN_MOD', 'Admin Modification'), ('REFUND', 'Refund'), ('FEE', 'Fee'), ('TRANSFER', 'Transfer'), ('INTEREST', 'Interest')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted - Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_REVISION', 'Needs Revision')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='websocketnotification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('TRANSACTION', 'Transaction'), ('BALANCE', 'Balance Update'), ('SYSTEM', 'System'), ('KYC', 'KYC Status Update')], default='INFO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['approved_by'], name='My_app_tran_approve_dcda8d_idx'),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
