# Generated by Django 5.2.10 on 2026-01-21 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0002_adminauditlog_alter_kycapplication_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('room_type', models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group Chat'), ('channel', 'Public Channel'), ('support', 'Support Room'), ('trade', 'Trade Discussion')], default='group', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('max_members', models.PositiveIntegerField(default=50)),
                ('requires_approval', models.BooleanField(default=False)),
                ('allow_invites', models.BooleanField(default=True)),
                ('allow_uploads', models.BooleanField(default=True)),
                ('allow_edits', models.BooleanField(default=True)),
                ('allow_deletes', models.BooleanField(default=True)),
                ('allow_pinning', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chat_room_avatars/')),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'ordering': ['-last_activity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=20)),
                ('is_muted', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_read', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Chat Room Member',
                'verbose_name_plural': 'Chat Room Members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notify_on_posts', models.BooleanField(default=True)),
                ('notify_on_trades', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Follow Relationship',
                'verbose_name_plural': 'Follow Relationships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment'), ('false_info', 'False Information'), ('trading_fraud', 'Trading Fraud'), ('other', 'Other')], max_length=50)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('action_taken', 'Action Taken'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('replies_count', models.PositiveIntegerField(default=0)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reported_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Comment',
                'verbose_name_plural': 'Social Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('analysis', 'Market Analysis'), ('trade_idea', 'Trade Idea'), ('question', 'Question'), ('news', 'Market News'), ('education', 'Educational'), ('discussion', 'Discussion'), ('achievement', 'Achievement'), ('review', 'Broker/Service Review')], default='discussion', max_length=50)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only'), ('private', 'Private')], default='public', max_length=20)),
                ('trading_symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('trade_direction', models.CharField(blank=True, choices=[('long', 'Long'), ('short', 'Short')], max_length=10, null=True)),
                ('timeframe', models.CharField(blank=True, choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week'), ('1M', '1 Month')], max_length=10, null=True)),
                ('position_size', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Position Size')),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trade_outcome', models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss'), ('breakeven', 'Break Even'), ('open', 'Still Open')], max_length=20, null=True)),
                ('pnl_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='P&L Amount')),
                ('pnl_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='P&L %')),
                ('post_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='published', max_length=20)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('bookmarks_count', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='post_videos/')),
                ('link_preview', models.JSONField(blank=True, default=dict)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reported_count', models.PositiveIntegerField(default=0)),
                ('is_under_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Social Post',
                'verbose_name_plural': 'Social Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('laugh', 'Laugh'), ('wow', 'Wow'), ('sad', 'Sad'), ('angry', 'Angry'), ('bullish', 'Bullish'), ('bearish', 'Bearish')], default='like', max_length=20)),
            ],
            options={
                'verbose_name': 'Post Like',
                'verbose_name_plural': 'Post Likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='adminauditlog',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='adminauditlog',
            name='target_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentGatewaySettings',
        ),
        migrations.RemoveField(
            model_name='planupgraderequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactionlimit',
            name='user_group',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='websocketnotification',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='broadcastmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Broadcast Message', 'verbose_name_plural': 'Broadcast Messages'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='My_app_tran_created_5eefa0_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='My_app_tran_gateway_535e0a_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='My_app_tran_payment_13f3d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='My_app_tran_currenc_b6236e_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='My_app_tran_expires_916e0b_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='My_app_tran_is_flag_f82b15_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='My_app_tran_approve_dcda8d_idx',
        ),
        migrations.RenameField(
            model_name='broadcastmessage',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='broadcastmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='read',
            new_name='is_delivered',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='broadcastmessage',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='broadcastmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='balancechange',
            name='trading_symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='broadcast_attachments/'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='broadcast_images/'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users'), ('kyc_verified', 'KYC Verified Users'), ('premium', 'Premium Users Only'), ('specific_plan', 'Specific Plan')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='target_plan',
            field=models.CharField(blank=True, choices=[('Starter', 'Starter - Basic features'), ('Pro', 'Pro - Advanced features'), ('Premium', 'Premium - All features + priority support'), ('Enterprise', 'Enterprise - Custom solutions')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='My_app.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post_like', 'Post Liked'), ('post_comment', 'New Comment'), ('new_follower', 'New Follower'), ('trade_update', 'Trade Update'), ('message', 'New Message'), ('system', 'System Notification'), ('achievement', 'Achievement Unlocked'), ('mention', 'You Were Mentioned')], default='system', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='push_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='community_username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_symbols',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reputation_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_online_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_trading_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_likes_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_posts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='trading_style',
            field=models.CharField(blank=True, choices=[('day_trader', 'Day Trader'), ('swing_trader', 'Swing Trader'), ('position_trader', 'Position Trader'), ('scalper', 'Scalper'), ('investor', 'Investor')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='emails_clicked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='emails_opened',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='emails_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('signup', 'Signup Form'), ('api', 'API'), ('import', 'Import'), ('other', 'Other')], default='website', max_length=50),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='losing_trades',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_trades',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='winning_trades',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balancechange',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('BONUS', 'Bonus'), ('ADMIN_MOD', 'Admin Modification'), ('REFUND', 'Refund'), ('FEE', 'Fee'), ('TRANSFER', 'Transfer'), ('INTEREST', 'Interest'), ('TRADE_PROFIT', 'Trade Profit'), ('TRADE_LOSS', 'Trade Loss')], max_length=20),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='broadcast_type',
            field=models.CharField(choices=[('system', 'System Announcement'), ('maintenance', 'Maintenance Notice'), ('update', 'Platform Update'), ('promotion', 'Promotion'), ('alert', 'Security Alert'), ('news', 'Market News')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('TRANSFER', 'Transfer'), ('FEE', 'Fee'), ('BONUS', 'Bonus'), ('REFUND', 'Refund'), ('INTEREST', 'Interest'), ('CHARGEBACK', 'Chargeback'), ('REVERSAL', 'Reversal'), ('ADMIN_MOD', 'Admin Modification'), ('TRADE_PROFIT', 'Trade Profit'), ('TRADE_LOSS', 'Trade Loss')], max_length=15),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['is_published', 'created_at'], name='My_app_broa_is_publ_7ef3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['broadcast_type'], name='My_app_broa_broadca_78bf48_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['target_audience'], name='My_app_broa_target__b247b5_idx'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_in_room', to='My_app.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='My_app.chatroom'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'receiver', 'created_at'], name='My_app_chat_sender__3e7f06_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='My_app_chat_sender__a5cdc4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['receiver', 'created_at'], name='My_app_chat_receive_27bf94_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_read', 'created_at'], name='My_app_chat_is_read_422683_idx'),
        ),
        migrations.AddField(
            model_name='chatroommember',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to='My_app.chatroom'),
        ),
        migrations.AddField(
            model_name='chatroommember',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroommember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='chat_rooms', through='My_app.ChatRoomMember', through_fields=('chat_room', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followrelationship',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followrelationship',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialcomment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='My_app.socialcomment'),
        ),
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='My_app.socialcomment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='My_app.socialcomment'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='My_app.socialpost'),
        ),
        migrations.AddField(
            model_name='socialcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='My_app.socialpost'),
        ),
        migrations.AddField(
            model_name='report',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='My_app.socialpost'),
        ),
        migrations.AddField(
            model_name='balancechange',
            name='trade_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_changes', to='My_app.socialpost'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='My_app.socialpost'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trade_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_transactions', to='My_app.socialpost'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='My_app_noti_user_id_794454_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at', 'status'], name='My_app_tran_created_c47ca6_idx'),
        ),
        migrations.AddField(
            model_name='socialpostlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='My_app.socialpost'),
        ),
        migrations.AddField(
            model_name='socialpostlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AdminAuditLog',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='PlanUpgradeRequest',
        ),
        migrations.DeleteModel(
            name='TransactionLimit',
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
        migrations.DeleteModel(
            name='WebSocketNotification',
        ),
        migrations.AlterUniqueTogether(
            name='chatroommember',
            unique_together={('chat_room', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_type', 'is_active'], name='My_app_chat_room_ty_c92ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['is_public', 'is_active'], name='My_app_chat_is_publ_f17bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['creator', 'created_at'], name='My_app_chat_creator_68948b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='followrelationship',
            unique_together={('follower', 'followed')},
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['author', 'created_at'], name='My_app_soci_author__023ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['post_type'], name='My_app_soci_post_ty_5d1017_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['trading_symbol'], name='My_app_soci_trading_a5cafb_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['is_active', 'created_at'], name='My_app_soci_is_acti_e87871_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['post_status'], name='My_app_soci_post_st_b50257_idx'),
        ),
        migrations.AddIndex(
            model_name='socialcomment',
            index=models.Index(fields=['post', 'created_at'], name='My_app_soci_post_id_ac2424_idx'),
        ),
        migrations.AddIndex(
            model_name='socialcomment',
            index=models.Index(fields=['author', 'created_at'], name='My_app_soci_author__3bee4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialpostlike',
            unique_together={('post', 'user')},
        ),
    ]
