# Generated by Django 5.2.10 on 2026-01-22 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0004_chatmessage_file_chatmessage_file_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User statuses',
            },
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='receiver_deleted',
            new_name='deleted_by_receiver',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender_deleted',
            new_name='deleted_by_sender',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='attachment_name',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='attachment_size',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_for_everyone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='ws_message_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Audio'), ('video', 'Video'), ('chart', 'Chart')], default='text', max_length=10),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_room', 'created_at'], name='My_app_chat_chat_ro_2dc977_idx'),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='typing_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typing_users', to='My_app.chatroom'),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='typing_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='being_typed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
